#------------------------------------------------------------------------------
# Title: Processing of raw beacon data
#
# Created by: Anna Crawford, Carleton University
#
# Date: 2014
#
# Modified by: 
#   Jill Rajewicz, April 26, 2018
#   Adam Garbo, March 21, 2019
#
# Project: Compilation and standardization of iceberg tracking beacon data
#
# Description: 
#   - Function to convert raw data from CALIB beacon with Argos transmitter. 
#   - Data is generated by the Argos2csv.py script that outputs a CSV from the 
#   Argos text file to a standardized CSV before further processing to 
#   'quality added' files. 
#   - Called on by beacon_processing.R  
#
# Necessary file(s): 
#   - Argos raw beacon data (CSV) 
#
# Notes: 
#   - Raw data should be kept in an 'input' directory with other raw data. 
#   - Values for sensor ranges are from CALIB Technical Manual.
#
#   Raw data columns (case sensitive):
#   ----------------------------------
#   - TransmitterID 
#   - WMO
#   - Latitude
#   - Longitude
#   - LocAccuracy
#   - SatelliteTime
#   - BeaconTime
#   - MessageIndex
#   - AtmPressure
#   - BattVoltage
#   - AirTemperature
#
#------------------------------------------------------------------------------

calib_argos_to_csv <- function(raw_data) {

  # Manufacturer sensor range values
  #---------------------------------
  vbat_max = 18.6
  vbat_min = 6.0
  ta_max = 26.5
  ta_min = -50.0
  bp_max = 1074.6
  bp_min = 920.0
  
  # Debug
  message("Standardizing: CALIB_ARGOS")
  
  # 1) Unique beacon identifier
  beacon_id <- filename
  
  # 2) Beacon type
  beacon_type <- "CALIB_ARGOS"
  
  # 3) Data timestamp (UTC)
  if("BeaconTime" %in% names(raw_data)) {
    datetime_data <- ymd_hms(raw_data$BeaconTime, truncated = 2)
  } else {
    datetime_data <- NA
  }
  
  # 4) Data transmission timestamp (UTC)
  if("SatelliteTime" %in% names(raw_data)) {
    datetime_transmit <- ymd_hms(raw_data$SatelliteTime, truncated = 2)
  } else {
    datetime_transmit <- NA
  }
  
  # 5) Latitude
  if("Latitude" %in% names(raw_data)) {
    latitude <- raw_data$Latitude
  } else {
    latitude <- NA
  }
  
  # 6) Longitude
  if("Longitude" %in% names(raw_data)) {
    longitude <- raw_data$Longitude
  } else {
    longitude <- NA
  }
  
  # 7) Battery voltage
  if("BattVoltage" %in% names(raw_data)) {
    vbat <- raw_data$BattVoltage
  } else {
    vbat <- NA
  }
  
  # 8) Air temperature
  if("AirTemperature" %in% names(raw_data)) {
    ta <- raw_data$AirTemperature
  } else {
    ta <- NA
  }
  
  # 11) Barometric pressure
  if("AtmPressure" %in% names(raw_data)) {
    bp <- raw_data$AtmPressure
  } else {
    bp <- NA
  }
  
  # 16) Location accuracy (Argos beacons)
  if("LocAccuracy" %in% names(raw_data)) {
    loc_accuracy <- raw_data$LocAccuracy
  } else {
    loc_accuracy <- NA
  }
  
  # 17) Message Index (Argos beacons)
  if("MessageIndex" %in% names(raw_data)) {
    message_index <- raw_data$MessageIndex
  } else {
    message_index <- NA
  }
  
  # Put the declared variables into a single data frame
  processed_data <- data.frame(beacon_id, beacon_type, datetime_data, 
                              datetime_transmit, latitude, longitude, vbat,
                              ta, bp, loc_accuracy, message_index, 
                              row.names=NULL)
  
  # Call data cleaning function
  cleaned_data <- clean_data(processed_data)
  
  # Standardize columns
  standardized_data <- standardize_columns(cleaned_data)
  
  # Calculate distance and speed
  standardized_data <- calculate_speed(standardized_data)
  
  # Choose file name
  output_file = filename
  
  # Choose output directory 
  setwd(output)
  write.csv(standardized_data, paste(output_file, ".csv", sep = ""), row.names=FALSE)
  
} # End function